### ISSUE TITLE
Debugger crashes in some cases when using static variable

### ISSUE THREAD

**Issue by csmuller** [neo-project/neo-debugger#128] opened 2021-06-17 13:50 UTC
I'm compiling and debugging a very simple contract that uses one static variable. When compiled with neow3j, the debugger stops without any errors at the line where the static variable is used. The contract looks like this:

In C#
```c#
[ContractPermission("*", "*")]
public class DotnetContract : SmartContract
{

    [InitialValue("NVq8SdaVYZ38QnGFV3ViDdFPubm21KG1An", ContractParameterType.Hash160)]
    static UInt160 owner = default;

    public static UInt160 method() {
        return owner;
    }

}
```

Or in Java
```java
@Permission(contract = "*", methods = "*")
public class ExampleContract {

    static Hash160 owner = addressToScriptHash("NVq8SdaVYZ38QnGFV3ViDdFPubm21KG1An");

    public static Hash160 method() {
        return owner;
    }
}
```

Most probable we do something wrong in neow3j, since debugging the same contract compiled with nccs works fine. But I  don't know what the problem is. Below are the debug info and scripts of the two compilers. Please take a look and see if you can find any mistakes in the produced artifacts.

A couple of things that might help:
- Debugging works if I make the `owner` variable local to the method.
- The debugger stops when it reaches the line with the `owner` var. So, if I add another line before, it will step through that line successfully and then stop at the next. E.g.
```java
    public static Hash160 method() {
        int i = 1;
        return owner;  <-- crashes here
    }
```

### Debug info

```json
{
  "hash": "0xc2dd5c15f6edcd5b4049b42c1c608d76bc8023c3",
  "documents": [
    "/path/to/the/contract/DotnetContract.cs"
  ],
  "static-variables": [
    "owner,Hash160,0"
  ],
  "methods": [
    {
      "id": "DotnetContract.method()",
      "name": "DotnetContract,method",
      "range": "0-3",
      "params": [],
      "return": "Hash160",
      "variables": [],
      "sequence-points": [
        "0[0]13:9-13:22",
        "3[0]14:5-14:6"
      ]
    }
  ],
  "events": []
}
```

### Script

```
LDSFLD0
JMP 02
RET
INITSSLOT 01
PUSHDATA1 20 6cc6e7aa712a83c1cdf097162f07adbb3c6e0261
STSFLD0
RET
```

### Debug Info

```json
{
  "hash": "4d00e5fbb6cdafb655d36e31697e6f2b3948a5e9",
  "documents": [
    "/path/to/the/contract/ExampleContract.java"
  ],
  "static-variables": [
    "owner,Hash160,0"
  ],
  "methods": [
    {
      "id": "io/neow3j/compiler/ExampleContract.<clinit>()V",
      "name": "io.neow3j.compiler.ExampleContract,_initialize",
      "range": "0-25",
      "params": [],
      "return": "Void",
      "variables": [],
      "sequence-points": [
        "2[0]20:0-20:0"
      ]
    },
    {
      "id": "io/neow3j/compiler/ExampleContract.method()Lio/neow3j/devpack/Hash160;",
      "name": "io.neow3j.compiler.ExampleContract,method",
      "range": "26-27",
      "params": [],
      "return": "Hash160",
      "variables": [],
      "sequence-points": [
        "26[0]23:0-23:0"
      ]
    }
  ],
  "events": []
}
```

### Script
```
INITSSLOT 01
PUSHDATA1 20 6cc6e7aa712a83c1cdf097162f07adbb3c6e0261
STSFLD0
RET
LDSFLD0
RET
```

**Comment by csmuller** [comment] 2021-06-17 13:52
Btw, you cannot reproduce this with the current neow3j version, because the code that produces the `static-variables` property in the debug info is not yet released.

**Comment by gsmachado** [comment] 2021-06-17 13:56
@csmuller once the PR is created in the [neow3j repo](https://github.com/neow3j/neow3j), link to this issue please. 👍

**Comment by gsmachado** [comment] 2021-06-18 10:09
the PR for this: https://github.com/neow3j/neow3j/pull/598

**Comment by devhawk** [comment] 2021-06-21 19:46
Nothing leaps out at me. Both binaries have a what looks like an initialization method that configures the static variable slot (INITSSLOT/PUSHDATA1/STSFLD0/RET) as well as a simple method implementation which is just LDSFLD0 and a RET. The C# version has a JMP 02 byte code, but I think that's basically a no-op (The JMP 2 operation is 2 bytes long, so I suspect that it merely jumps over iteself)

**Comment by csmuller** [comment] 2021-06-22 07:04
I agree that judging by the VM script, both do the same.

Here are the binaries (incl. debuginfo and manifest):
[neow3j-contract.zip](https://github.com/neo-project/neo-debugger/files/6691942/neow3j-contract.zip)
[nccs-contract.zip](https://github.com/neo-project/neo-debugger/files/6691944/nccs-contract.zip)

**Comment by csmuller** [comment] 2021-07-05 16:17
@devhawk, where you able to reproduce the crash with the neow3j binary?

**Comment by devhawk** [comment] 2021-07-07 17:58
I don't have the java source handy and I don't have a neow3j environment, but I was able to step thru the disassembly view of the calling script and get a result. 

```
Gas Consumed: 0.0098487
Return: "6cc6e7aa712a83c1cdf097162f07adbb3c6e0261"
```

I am going to figure out why I can't step thru the disassmbly of your contract proper, but I'm not crashing in VSCode the way you describe

**Comment by devhawk** [comment] 2021-07-07 19:02
FYI, figured out the issue w/ the disassembly. SInce I had the debug info the disassembler emits comments for method start/end and sequence points. However, since I didn't have the source, the sequence point -> code mapping was throwing. that will be fixed in a future release of the debugger. 

Other than the disassmbler issue described above, I had no issue stepping thru the code in the disassembler. Will try on my mac

**Comment by devhawk** [comment] 2021-07-07 19:12
> Other than the disassmbler issue described above, I had no issue stepping thru the code in the disassembler. Will try on my mac

I was also able to step thru the code in source view on my windows machine (though I discovered a bug in the source map code)

**Comment by devhawk** [comment] 2021-07-07 20:44
could not reproduce on my M1 Mac Mini

**Comment by qvanphong** [comment] 2022-01-01 03:55
Hi, any updates on this issue? It is happening in my work right now.
Specifically is happening in `Storage.getInteger` static method

```java
	private static int getBalance(Hash160 account) {
		Integer balance = Storage.getInteger(sc, account.toByteArray());
		return balance != null ? balance : 0;
	}
```

My project was build and compiled by neow3j

**Comment by csmuller** [comment] 2022-01-03 16:31
> Hi, any updates on this issue?

No updates yet. I will look into it again.

**Comment by csmuller** [comment] 2022-01-06 15:00
This issue is still a mystery to me. The only thing I can say is that the problem seems related to loading static fields (`LDSFLD`). The debugger suddenly stops as soon as it hits a line that loads a static field.

**Comment by gsmachado** [comment] 2022-01-06 16:57
@devhawk do you think that could be a platform issue? I mean, @csmuller and I are with MacOS. Did you try on vscode for MacOS, somehow?

Or, maybe, we could try on Windows.

**Comment by csmuller** [comment] 2022-01-06 16:58
@gsmachado, devhawk mentioned somewhere above that he tested on MacOS.

Anyway, at this point, i have to read Neo debugger code to find out more. But I don't have the time for this currently.

**Comment by gsmachado** [comment] 2022-01-06 16:58
@qvanphong oh... could you please provide us with more information about your environment?

For example:
- VSCode version
- Neo Development Toolkit version
- neow3j version
- Operating System version

**Comment by devhawk** [comment] 2022-01-06 17:01
I have a mac and as per an earlier comment couldn't reproduce. But I can try again. Is the crash consistent? What is a good neow3j contract to use for testing?

**Comment by csmuller** [comment] 2022-01-06 17:26
I just pushed a simple example to the develop branch of our examples repo: https://github.com/neow3j/neow3j-examples-java/blob/develop/src/main/java/io/neow3j/examples/contractdevelopment/contracts/ExampleContract.java

You can pull the repo https://github.com/neow3j/neow3j-examples-java and checkout the `develop` branch.
Execute `gradlew.bat neow3jCompile` in the project's root. That should compile the Example contract and place NEF, manifest, and debug info in the *./build/neow3j* directory. There's an launch config called "ExampleContract" in *launch.config* that you can use to start debugging the contract.

**Comment by qvanphong** [comment] 2022-01-07 03:39
> @qvanphong oh... could you please provide us with more information about your environment?
> 
> For example:
> 
> * VSCode version
> * Neo Development Toolkit version
> * neow3j version
> * Operating System version

Vscode: 1.63.2
Neo Development Toolkit: [2.0-preview] - 2021-03-24
neow3j - 3.14.1
OS: Windows 11 - 21H2

**Comment by gsmachado** [comment] 2022-01-07 10:41
> 
> Vscode: 1.63.2 Neo Development Toolkit: [2.0-preview] - 2021-03-24 neow3j - 3.14.1 OS: Windows 11 - 21H2
>

Oh, thanks!

@devhawk then, it seems it's NOT a platform-dependent issue given that with Windows it's also reproducible.

**Comment by devhawk** [comment] 2022-02-15 20:30
No, I've been working on other stuff. I'll look now

**Comment by devhawk** [comment] 2022-02-15 20:52
I setup a debian WSL image, installed OpenJDK 11, cloned the repo @csmuller pointed me to, checked out the last commit before ExampleContract was removed and tried debugging. No problem. I will try moving the compiled code to Windows and Mac to try and repro the problem

**Comment by devhawk** [comment] 2022-02-15 20:53
If someone could share a project that fails on their machine - including the compiled NEF, manifest and dbgnfo file, that would help me

**Comment by devhawk** [comment] 2022-08-15 19:14
it's been several months since there's been any communication on this issue. since there's no repro, I'm not sure what else can be done.

**Closed** 2022-08-15 19:15 UTC
Labels: wontfix
